name: Deploy via SSH

on:
  workflow_run:
    workflows: ["Build and Push to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 34002
          script: |
            docker pull saepulid07/nimestreamapi-backend:latest

            docker stop nimestreamapi-backend || true
            docker rm nimestreamapi-backend || true

            docker run -d \
              --name nimestreamapi-backend \
              --env-file /root/NimeStreamAPIDev/.env \
              -p 3000:3000 \
              saepulid07/nimestreamapi-backend:latest
