name: Deploy via SSH

on:
  workflow_run:
    workflows: ["Build and Push to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 34002
          script: |
            cd /root/NimeStreamAPIDev

            # Pull latest image from Docker Hub
            docker compose pull

            # Stop and remove running containers
            docker compose down

            # Rebuild and start services with latest image
            docker compose up -d --remove-orphans
